/* Auto-generated by genmsg_cpp for file /home/robofriend/ros_workspace/hcr_vip/msg/location_msg.msg */
#ifndef HCR_VIP_MESSAGE_LOCATION_MSG_H
#define HCR_VIP_MESSAGE_LOCATION_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hcr_vip
{
template <class ContainerAllocator>
struct location_msg_ {
  typedef location_msg_<ContainerAllocator> Type;

  location_msg_()
  : location()
  {
  }

  location_msg_(const ContainerAllocator& _alloc)
  : location(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  location;


private:
  static const char* __s_getDataType_() { return "hcr_vip/location_msg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "03da474bc61cfeb81a8854b4ca05bafa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string location\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, location);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, location);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(location);
    return size;
  }

  typedef boost::shared_ptr< ::hcr_vip::location_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hcr_vip::location_msg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct location_msg
typedef  ::hcr_vip::location_msg_<std::allocator<void> > location_msg;

typedef boost::shared_ptr< ::hcr_vip::location_msg> location_msgPtr;
typedef boost::shared_ptr< ::hcr_vip::location_msg const> location_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hcr_vip::location_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hcr_vip::location_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hcr_vip

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hcr_vip::location_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hcr_vip::location_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hcr_vip::location_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "03da474bc61cfeb81a8854b4ca05bafa";
  }

  static const char* value(const  ::hcr_vip::location_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x03da474bc61cfeb8ULL;
  static const uint64_t static_value2 = 0x1a8854b4ca05bafaULL;
};

template<class ContainerAllocator>
struct DataType< ::hcr_vip::location_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hcr_vip/location_msg";
  }

  static const char* value(const  ::hcr_vip::location_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hcr_vip::location_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string location\n\
\n\
";
  }

  static const char* value(const  ::hcr_vip::location_msg_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hcr_vip::location_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.location);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct location_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hcr_vip::location_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hcr_vip::location_msg_<ContainerAllocator> & v) 
  {
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HCR_VIP_MESSAGE_LOCATION_MSG_H

